fix: correct grades minmax values
openedx/frontend-app-gradebook pull request #277
Opened 2022-10-12 14:28 UTC by dyudyunov

When the assignment type is selected, but the assignment id isn't - the courseGradeMax, courseGradeMin assignmentGradeMax and assignmentGradeMin values become nullable. This leads to incorrect filtering results.

The issue demo:
![gradebook_filters](https://user-images.githubusercontent.com/47273130/195368475-796db248-df43-4940-b6c0-bb525de8b3b6.gif)

Fix:
- Preserve the courseGradeMax and courseGradeMin values in such cases;

The fix demo:
![gradebook_filters_fix](https://user-images.githubusercontent.com/47273130/195368551-12201b2a-a801-4d53-a2c6-f1a37c038c4a.gif)

2022-10-12 14:28 UTC, openedx-webhooks commented
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-10-12 14:28 UTC, dyudyunov commented
@natabene hi

the PR is ready for the review

2022-12-27 08:49 UTC, dyudyunov commented
77 days from the opening of the PR and no reaction at all (

2022-12-27 16:15 UTC, mphilbrick211 commented
@jmakowski1123 looks like this needs Product review. Since this PR has been open a while, please make you/Ryan check in on this soon.

CC: @mattcarter - heads-up on this for when Product review has been completed.

2023-01-12 15:40 UTC, ProductRyan commented
@dyudyunov This change makes sense from a product POV. I've created an internal JIRA ticket for eng review
https://2u-internal.atlassian.net/browse/AU-998

2023-01-18 11:12 UTC, dyudyunov commented
created a [PR to olive.master](https://github.com/openedx/frontend-app-gradebook/pull/303) with the same fix

2023-01-20 19:59 UTC, jansenk requested changes
Echoing the other PR. There's a failing test here that isn't showing up in CI because for some reason tests aren't running against this PR.

2023-01-24 10:28 UTC, dyudyunov commented
@jansenk tests are corrected, please proceed with the review

2023-01-24 18:50 UTC, jansenk approved these changes

2023-01-24 18:50 UTC, merged

2023-01-24 18:51 UTC, openedx-webhooks commented
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/277&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2022-10-12+14:28&entry.1917517419=2023-01-24+18:50&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->