fix: replace Field.Email reference for Field.Text
openedx/frontend-app-gradebook pull request #345
Opened 2023-08-07 16:02 UTC by dcoa

**Description**
The master branch doesn't have the references to new Field.Text updated, there is a screenshot of the error 

![image](https://github.com/openedx/frontend-app-gradebook/assets/66016493/4a8e0014-9c24-4183-b67f-bc2444472b34)

As well `useGradeButtonData` doesn't return  a string in the label field is returning a function, so the numbers weren't render 
![image](https://github.com/openedx/frontend-app-gradebook/assets/66016493/60ef3ca5-daad-4a9e-bba2-b03b156f38e4)

This PR tries to solve that rendering situation. 

**What changed?**

- Update the reference for Field.Email to Field.Text
- Update the test.
- 
**Developer Checklist**
- [ ] Test suites passing
- [ ] Documentation and test plan updated, if applicable
- [ ] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @openedx/content-aurora

2023-08-07 16:02 UTC, openedx-webhooks commented
Thanks for the pull request, @dcoa!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-09-02 22:31 UTC, arslanashraf7 commented
Hey @mphilbrick211 we are facing the same issue while running the gradebook locally and on a server. Is it possible by any chance that the review on this PR could be prioritized?

2023-09-06 02:48 UTC, mphilbrick211 commented
> Hey @mphilbrick211 we are facing the same issue while running the gradebook locally and on a server. Is it possible by any chance that the review on this PR could be prioritized?

Hi @openedx/content-aurora! Flagging this - would someone be able to please review?

2023-09-12 11:02 UTC, dcoa commented
@muselesscreator  @leangseu-edx 

Hi folks,  could you help us with a review in his PR or help us identify the right reviewer?

2023-09-21 19:01 UTC, arbrandes requested changes
The changes make sense, but I'm worried the bugs they fix weren't caught by any tests to begin with.  Would it be too much to ask to add some tests that would've done so?

2023-09-24 11:55 UTC, dcoa commented
Hi @arbrandes thank you for your review and not 100% sure to understand your request because when I used the branch I realized that the reason why the test didn't catch the errors was because the testing for this component and function was correct: [Field.Text test ](https://github.com/openedx/frontend-app-gradebook/blob/247e9f3668cdf8c918f9bed7cb6fd2cdf2e9de6f/src/components/GradesView/GradebookTable/Fields.test.jsx#L44) and [subsectionGrade test](https://github.com/openedx/frontend-app-gradebook/blob/247e9f3668cdf8c918f9bed7cb6fd2cdf2e9de6f/src/data/redux/transforms.test.js#L28C9-L28C9) only the reference was not updated and not fail because of the use of `jest.mock`. 

I updated the test reference too.

2023-09-25 14:09 UTC, arbrandes commented
Yeah, it might be going overboard to test for this retroactively, here.  I feel like it would initiate a full revamp, which would probably be better planned elsewhere.  (As part of the migration to react-testing-library, perhaps.)  Let's just fix the glaring issue and move on, for now.

2023-09-25 14:09 UTC, arbrandes approved these changes

2023-09-25 14:10 UTC, merged

2023-09-25 14:10 UTC, openedx-webhooks commented
@dcoa 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-gradebook&entry.867055334=https://github.com/openedx/frontend-app-gradebook/pull/345&entry.1484655318=https://github.com/dcoa&entry.752974735=2023-08-07+16:02&entry.1917517419=2023-09-25+14:10&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->