fix: Fix rows counter in the Edit Grade modal window
openedx/frontend-app-gradebook pull request #389
Opened 2024-04-04 20:45 UTC by Lunyachek

This is backport from master - https://github.com/openedx/frontend-app-gradebook/pull/310

**TL;DR -** The problem was in the rows counter in the Edit Grades modal window. First digit - number of lines excluding the last line with the form. Second digit - grades data. And our proposal is to include last row with form to common counting

<img width="1904" alt="Снимок экрана 2023-02-10 в 15 25 06" src="https://user-images.githubusercontent.com/19806032/218103195-661c7642-72cb-49bd-be9a-bfe7f8fd0eb3.png">

**What changed?**

<img width="1904" alt="Снимок экрана 2023-02-10 в 15 42 01" src="https://user-images.githubusercontent.com/19806032/218106655-0a52059c-4041-4c5d-935a-9c89b8183bc2.png">

FYI: @openedx/content-aurora

2024-04-04 20:45 UTC, openedx-webhooks commented
Thanks for the pull request, @Lunyachek! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-07-25 21:35 UTC, mphilbrick211 commented
Hi @farhaanbukhsh! The master for this PR has been merged, so this one should be good-to-go. Thanks!

2024-07-26 06:07 UTC, farhaanbukhsh commented
@mphilbrick211 sure will merge this after testing :)

2024-08-01 19:37 UTC, farhaanbukhsh requested changes
Hey @Lunyachek  can you have look at the comment and test it. Thanks a lot for the PR. Let me know if you need more clarification.

2024-08-01 19:37 UTC, farhaanbukhsh commented on src/components/GradesView/EditModal/OverrideTable/index.jsx
> +  ];
should we put a check on the data something like 

```suggestion
    const tableData = data ? [
    ...data,
    {
      adjustedGrade: <AdjustedGradeInput />,
      date: formatDateForDisplay(new Date()),
      reason: <ReasonInput />,
    },
  ] : [];
```

While testing I landed up on error when data was undefined and this happened multiple times mostly I guess when the states were getting updated.

2024-08-01 19:40 UTC, farhaanbukhsh commented on src/components/GradesView/EditModal/OverrideTable/index.jsx
> +  ];
![Peek 2024-08-02 01-09](https://github.com/user-attachments/assets/70a6c55a-89b3-420e-9410-f176d1ec148b)

2024-08-01 19:40 UTC, farhaanbukhsh commented
> Hi @farhaanbukhsh! The master for this PR has been merged, so this one should be good-to-go. Thanks!

hey @mphilbrick211 I have reviewed the PR and added few suggestion and changes

2024-08-02 20:19 UTC, farhaanbukhsh commented on src/components/GradesView/EditModal/OverrideTable/index.jsx
> +  ];
We should backport https://github.com/openedx/frontend-app-gradebook/commit/4e9270ab8eb6a2e41fa2f4d01e29bfc14a6e165b

2024-08-26 20:32 UTC, mphilbrick211 commented
> > Hi @farhaanbukhsh! The master for this PR has been merged, so this one should be good-to-go. Thanks!
> 
> hey @mphilbrick211 I have reviewed the PR and added few suggestion and changes

Thanks, @farhaanbukhsh! 

Flagging this for you, @Lunyachek!

2024-10-28 11:03 UTC, farhaanbukhsh commented
@Lunyachek can you please backport the additional commit so that we can safely merge the PR?

2024-12-10 19:45 UTC, mphilbrick211 commented
> @Lunyachek can you please backport the additional commit so that we can safely merge the PR?

@Lunyachek friendly ping on this

2025-01-26 10:45 UTC, Lunyachek commented
@mphilbrick211 Hi! Commit has been backported

2025-01-26 16:03 UTC, farhaanbukhsh approved these changes
👍

- ✅ I tested this on tutor devstack
- ✅ I read through the code
- ❌ I checked for accessibility issues
- ❌ Includes documentation

2025-01-26 16:04 UTC, merged

2025-01-26 16:04 UTC, farhaanbukhsh commented
thanks @Lunyachek  for the effort and persistence.