feat: Assignment and course grade fields validations (redwood.master)
openedx/frontend-app-gradebook pull request #396
Opened 2024-06-05 11:28 UTC by vladislavkeblysh

- Added min max validations to assignments grade fields
- Added validations when min value must be less than max value

![Screenshot 2023-10-21 at 15 02 27](https://github.com/openedx/frontend-app-gradebook/assets/138868841/0dc19c5a-4ff8-4197-a323-35906b3b22e0)
![Screenshot 2023-10-21 at 15 02 42](https://github.com/openedx/frontend-app-gradebook/assets/138868841/2c305423-27db-4fa0-b8ed-36992b8010ba)

2024-06-05 11:28 UTC, openedx-webhooks commented
Thanks for the pull request, @vladislavkeblysh! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-06-05 21:30 UTC, mphilbrick211 commented
Hi @vladislavkeblysh! A few branch conflicts have popped up.

2024-07-30 20:38 UTC, mphilbrick211 commented
> Hi @vladislavkeblysh! A few branch conflicts have popped up.

Hi @vladislavkeblysh - friendly ping on this!

2024-07-31 13:46 UTC, vladislavkeblysh commented
@mphilbrick211  done!

2024-08-02 13:41 UTC, farhaanbukhsh commented
@vladislavkeblysh  there  are still conflicts and tests failing can you please resolve them :) I can review it then :)

2024-08-02 13:45 UTC, farhaanbukhsh requested changes
I think the rebase didn't go the right way can you please check once.

2024-08-02 13:45 UTC, farhaanbukhsh commented on catalog-info.yaml
> +  lifecycle: 'experimental'
This file is not related to the PR

2024-10-28 11:01 UTC, farhaanbukhsh commented
Based on #366

2024-12-10 19:51 UTC, mphilbrick211 commented
Hi @vladislavkeblysh @farhaanbukhsh! Is this still in progress?

2025-02-17 10:31 UTC, vladislavkeblysh commented
@farhaanbukhsh can you run CI pls?

2025-09-16 20:03 UTC, mphilbrick211 commented
Closing, as we're no longer backporting to Redwood.

Can reopen if needed. Thanks!

2025-09-16 20:03 UTC, closed without merging